title: My Portfolio of UX and Design
description: Collection of student and freelance works
show_downloads: false
theme: jekyll-theme-cayman
baseurl: "/il-mio-portfolio" # the subpath of the site
url: ""

#Github Repo
repo_name: il-mio-portfolio
branch: master

# Build settings
markdown: kramdown
highlighter: rouge
